package cps450;

public enum SemanticError {
	UNDECLAREDVAR, UNDECLAREDMETHOD, REDECLAREDVAR, REDECLAREDMETHOD, WRONGPARAMNUM,
	MORETHANONECLASS, UNSUPPORTED, INCORRECTTYPE, TYPEMISMATCH, 
	LOOPTESTNOTBOOL, WRONGPARAMTYPE, TYPENOTSPECIFIED, NOSUCHMETHODINCLASS, NOSTARTMETHOD

}
